# ============================================================
# prepare_fast_subset.py — Pre-resize a selected subset so CPU training is not
# bottlenecked on JPEG decoding.
#
# smashspeed ships native 1920x1080 (some 4K) frames. Ultralytics decodes and
# resizes every image on every epoch, and on this laptop it reported
# "Using 0 dataloader workers", so that cost is serialised with compute.
# Measured: 7.1 s/iteration = ~17.7 min/epoch for 1200 images, i.e. 0.89 s per
# image per epoch — 2.5x the 0.35 s recorded for v2, whose export was already
# 416x416.
#
# Resizing once to a 640 long side cuts the decoded pixel count ~9x. YOLO labels
# are NORMALISED (cx cy w h as fractions), so they are copied unchanged — the
# resize cannot desynchronise boxes from images.
#
# RAM caching (ultralytics cache=True) was rejected: only ~1.8 GB was free and
# 1200 cached 640x640 frames need ~1.5 GB, which would swap.
#
# Usage:  python scripts/prepare_fast_subset.py --root datasets/smashspeed-v8
# ============================================================

import argparse
import os
import random
import shutil
import sys

import cv2


def resize_into(paths, out_img_dir, out_lbl_dir, src_lbl_dir, side, note):
    os.makedirs(out_img_dir, exist_ok=True)
    os.makedirs(out_lbl_dir, exist_ok=True)
    done = 0
    for i, p in enumerate(paths):
        if i and i % 300 == 0:
            print(f"    {note} {i}/{len(paths)}", flush=True)
        im = cv2.imread(p)
        if im is None:
            continue
        h, w = im.shape[:2]
        scale = side / float(max(h, w))
        if scale < 1.0:
            im = cv2.resize(im, (max(1, int(round(w * scale))),
                                 max(1, int(round(h * scale)))),
                            interpolation=cv2.INTER_AREA)
        stem = os.path.splitext(os.path.basename(p))[0]
        cv2.imwrite(os.path.join(out_img_dir, stem + ".jpg"), im,
                    [cv2.IMWRITE_JPEG_QUALITY, 92])

        # Normalised labels are resolution independent - copy verbatim.
        src_lbl = os.path.join(src_lbl_dir, stem + ".txt")
        dst_lbl = os.path.join(out_lbl_dir, stem + ".txt")
        if os.path.isfile(src_lbl):
            shutil.copyfile(src_lbl, dst_lbl)
        else:
            open(dst_lbl, "w").close()  # background frame
        done += 1
    return done


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--list", default=None,
                    help="train_selected.txt from select_training_subset.py "
                         "(defaults to <root>/train_selected.txt)")
    ap.add_argument("--side", type=int, default=640)
    ap.add_argument("--max-val", type=int, default=400,
                    help="cap the validation set. It is re-run every epoch, so "
                         "2000+ full-HD frames cost as much as the training.")
    ap.add_argument("--out", default=None,
                    help="output dataset dir (default <root>-fast)")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    list_path = args.list or os.path.join(args.root, "train_selected.txt")
    if not os.path.isfile(list_path):
        print(f"[ERROR] {list_path} not found - run "
              f"scripts/select_training_subset.py first", file=sys.stderr)
        return 1

    out = args.out or (args.root.rstrip("/\\") + "-fast")
    train_imgs = [l.strip() for l in open(list_path) if l.strip()]
    print(f"[PREP] {len(train_imgs)} training images -> {args.side}px long side")

    n_tr = resize_into(
        train_imgs,
        os.path.join(out, "train", "images"), os.path.join(out, "train", "labels"),
        os.path.join(args.root, "train", "labels"), args.side, "train")

    val_dir = "valid" if os.path.isdir(os.path.join(args.root, "valid")) else "val"
    val_src = os.path.join(args.root, val_dir, "images")
    val_imgs = sorted(
        os.path.join(val_src, f) for f in os.listdir(val_src)
        if f.lower().endswith((".jpg", ".jpeg", ".png")))
    random.Random(args.seed).shuffle(val_imgs)
    val_imgs = val_imgs[:args.max_val]
    print(f"[PREP] {len(val_imgs)} validation images")

    n_va = resize_into(
        val_imgs,
        os.path.join(out, "valid", "images"), os.path.join(out, "valid", "labels"),
        os.path.join(args.root, val_dir, "labels"), args.side, "valid")

    yaml_path = os.path.join(out, "data.yaml")
    with open(yaml_path, "w") as fh:
        fh.write(f"# Generated by scripts/prepare_fast_subset.py from {args.root}\n"
                 f"# Images pre-resized to {args.side}px long side; labels are\n"
                 f"# normalised so they were copied unchanged.\n"
                 f"train: {os.path.abspath(os.path.join(out, 'train', 'images'))}\n"
                 f"val: {os.path.abspath(os.path.join(out, 'valid', 'images'))}\n"
                 f"\nnc: 1\nnames: ['Shuttlecock']\n")

    print(f"[DONE] train {n_tr}  valid {n_va}  -> {out}")
    print(f"[NEXT] python scripts/train_shuttlecock_v2.py --data {yaml_path} "
          f"--epochs 15 --name yolov8n-640-v3-smashspeed "
          f"--deploy-to models/shuttlecock_v3.pt")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
