# ============================================================
# select_training_subset.py — Pick training images by SHUTTLE SIZE, not at random.
#
# train_shuttlecock_v2.py caps the run via ultralytics' `fraction`, which
# subsamples RANDOMLY. On smashspeed that is a bad deal: 69% of labelled frames
# have a shuttle under 12 px at imgsz 640 — near YOLOv8's detection floor (the
# finest stride is 8) and further away than the feeder camera will ever be. A
# random 1200 would spend most of the run on the hardest, least relevant frames.
#
# This selects frames whose shuttle falls in the size range the deployed camera
# actually produces (measured: ~36 px at 1 m on the laptop webcam at imgsz 640),
# and keeps a share of BACKGROUND frames — images with no shuttle at all. Those
# matter: the current v2 weights fire on blank walls at 0.73 confidence, and
# negative examples are what suppress that.
#
# Writes an image-list txt plus a data.yaml pointing at it; nothing is copied or
# moved, so the full dataset stays intact for later runs.
#
# Usage:  python scripts/select_training_subset.py --root datasets/smashspeed-v8
#         python scripts/select_training_subset.py --root ... --min-px 20 --max-images 1200
# ============================================================

import argparse
import glob
import os
import random
import sys


def max_box_px(label_path: str, imgsz: int):
    """Widest box in the label, as pixels at imgsz. None = no label file.

    Returns 0.0 for a background frame (label file present but empty).
    """
    if not os.path.isfile(label_path):
        return None
    widest = 0.0
    for line in open(label_path):
        parts = line.split()
        if len(parts) >= 5:
            widest = max(widest, float(parts[3]) * imgsz)
    return widest


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--min-px", type=float, default=20.0,
                    help="keep frames whose shuttle is at least this wide at "
                         "--imgsz. Default 20 matches ~1 m on the test webcam.")
    ap.add_argument("--max-px", type=float, default=0.0,
                    help="optional upper bound; 0 disables it")
    ap.add_argument("--max-images", type=int, default=1200,
                    help="CPU budget: ~0.35 s per image per epoch on this machine")
    ap.add_argument("--background-share", type=float, default=0.25,
                    help="fraction of the selection that should be frames with "
                         "no shuttle, to suppress false positives")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    idir = os.path.join(args.root, "train", "images")
    ldir = os.path.join(args.root, "train", "labels")
    if not os.path.isdir(idir):
        print(f"[ERROR] no train/images under {args.root}", file=sys.stderr)
        return 1

    positives, backgrounds = [], []
    for p in sorted(glob.glob(os.path.join(idir, "*.*"))):
        stem = os.path.splitext(os.path.basename(p))[0]
        w = max_box_px(os.path.join(ldir, stem + ".txt"), args.imgsz)
        if w is None:
            continue
        if w == 0.0:
            backgrounds.append(p)
        elif w >= args.min_px and (args.max_px <= 0 or w <= args.max_px):
            positives.append(p)

    print(f"[SCAN] {len(positives)} frames with shuttle >= {args.min_px:.0f} px "
          f"@{args.imgsz}   |   {len(backgrounds)} background frames")

    if not positives:
        print("[ERROR] nothing matched - lower --min-px", file=sys.stderr)
        return 1

    rng = random.Random(args.seed)
    n_bg = int(args.max_images * args.background_share)
    n_pos = args.max_images - n_bg

    rng.shuffle(positives)
    rng.shuffle(backgrounds)
    chosen = positives[:n_pos] + backgrounds[:n_bg]
    rng.shuffle(chosen)

    n_pos_used = min(len(positives), n_pos)
    n_bg_used = min(len(backgrounds), n_bg)
    print(f"[PICK] {n_pos_used} positives + {n_bg_used} backgrounds "
          f"= {len(chosen)} training images")
    hours = len(chosen) * 0.35 * 80 / 3600.0
    print(f"[COST] ~{hours:.1f} h for 80 epochs on this CPU "
          f"(~{hours / 80 * 15:.1f} h for a 15-epoch smoke run)")

    list_path = os.path.join(args.root, "train_selected.txt")
    with open(list_path, "w") as fh:
        fh.write("\n".join(os.path.abspath(p) for p in chosen) + "\n")

    val_dir = ("valid" if os.path.isdir(os.path.join(args.root, "valid"))
               else "val")
    yaml_path = os.path.join(args.root, "data_selected.yaml")
    with open(yaml_path, "w") as fh:
        fh.write(
            f"# Generated by scripts/select_training_subset.py\n"
            f"# shuttle >= {args.min_px:.0f}px @{args.imgsz}, "
            f"{n_bg_used} background frames included.\n"
            f"train: {os.path.abspath(list_path)}\n"
            f"val: {os.path.abspath(os.path.join(args.root, val_dir, 'images'))}\n"
            f"test: {os.path.abspath(os.path.join(args.root, 'test', 'images'))}\n"
            f"\nnc: 1\nnames: ['Shuttlecock']\n")

    print(f"[DONE] {list_path}")
    print(f"[DONE] {yaml_path}")
    print(f"[NEXT] python scripts/train_shuttlecock_v2.py --data {yaml_path} "
          f"--epochs 15")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
